apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      volumes:
      - name: postgres-vl
        persistentVolumeClaim:
          claimName: postgres-vl
      containers:
      - name: ping
        image: dreamteamestiam/ping:latest
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: "strapi"
        - name: POSTGRES_USER
          value: "dreamteam"
        - name: POSTGRES_PASSWORD
          value: "dreamteampasswd"
        - name: VERBOSITY
          value: "verbose"
        - name: PGDATA
          value: "/var/lib/postgresql/data"  
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-vl
          mountPath: /var/lib/postgresql/data
      - name: strapi
        image: dreamteamestiam/backend:latest
        env:
        - name: DATABASE_CLIENT
          value: "postgres"
        - name: DATABASE_HOST
          value: "app"
        - name: DATABASE_PORT
          value: "30001"
        - name: DATABASE_NAME
          value: "strapi"
        - name: DATABASE_USERNAME
          value: "dreamteam"
        - name: DATABASE_PASSWORD
          value: "dreamteampasswd"
        ports:
        - containerPort: 1337
      - name: vue
        image: dreamteamestiam/frontend:latest
        env:
        - name: API_URL
          value: "http://lol.permafrhost.fr:1337"
        ports:
        - containerPort: 3000