apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: postgres-vlc
        persistentVolumeClaim:
          claimName: postgres-vlc
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: "strapi"
        - name: POSTGRES_USER
          value: "dreamteam"
        - name: POSTGRES_PASSWORD
          value: "dreamteampasswd"
        - name: VERBOSITY
          value: "verbose"
        - name: PGDATA
          value: "/var/lib/postgresql/data"  
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-vlc
          mountPath: /var/lib/postgresql/data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
      - name: strapi
        image: dreamteamestiam/backend:latest
        env:
        - name: DATABASE_CLIENT
          value: "postgres"
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "strapi"
        - name: DATABASE_USERNAME
          value: "dreamteam"
        - name: DATABASE_PASSWORD
          value: "dreamteampasswd"
        ports:
        - containerPort: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
      - name: vue
        image: dreamteamestiam/frontend:latest
        env:
        - name: API_URL
          value: "http://178.32.215.77:1337"
        ports:
        - containerPort: 3000