apiVersion: v1
kind: Service
metadata:
  name: svc-postgres
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: expose-postgres
    nodePort: 30001
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: svc-strapi
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: expose-strapi
    nodePort: 30002
    port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: strapi
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: svc-vue
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: expose-vue
    nodePort: 30003
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: vue
  sessionAffinity: None
  type: LoadBalancer