apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: port-1
    nodePort: 30001
    port: 5432
    protocol: TCP
    targetPort: 5432
  - name: port-2
    nodePort: 30002
    port: 1337
    protocol: TCP
    targetPort: 1337
  - name: port-3
    nodePort: 30003
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: strapi
  sessionAffinity: None
  type: LoadBalancer
