apiVersion: v1
kind: PersistentVolume
metadata:
  name: strapi-vl
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: Pod
metadata:
  name: strapi-postgres
spec:
  volumes:
    - name: strapi-vl
      persistentVolumeClaim:
        claimName: strapi-vl
  containers:
  - name: strapi
    image: strapi/strapi:latest
    env:
    - name: DATABASE_CLIENT
      value: "postgres"
    - name: DATABASE_HOST
      value: "postgres"
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: "strapi"
    - name: DATABASE_USERNAME
      value: "dreamteam"
    - name: DATABASE_PASSWORD
      value: "dreamteampasswd"
    ports:
    - containerPort: 1337
    volumeMounts:
    - name: strapi-vl
      mountPath: /srv/app
  - name: postgres
    image: postgres:latest
    envFrom:
    - configMapRef:
      name: postgres-config
    ports:
    - containerPort: 5432
      name: postgredb
    volumeMounts:
    - name: postgredb
      mountPath: /var/lib/postgresql/data
      subPath: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: strapi
  labels:
    run: strapi
spec:
  ports:
  - port: 1337
    protocol: TCP
  selector:
    run: strapi

