apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
      - name: strapi
        image: strapi/strapi:latest
        env:
        - name: DATABASE_CLIENT
          value: "postgres"
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "strapi"
        - name: DATABASE_USERNAME
          value: "dreamteam"
        - name: DATABASE_PASSWORD
          value: "dreamteampasswd"
        ports:
        - containerPort: 1337
