apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-vlc
  namespace: dreamteam-deliveroo
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-vlc
  namespace: dreamteam-deliveroo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi